spring.datasource.url=jdbc:postgresql://localhost:5432/bmt
spring.datasource.username=bmt_user
spring.datasource.password=4777

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.thymeleaf.cache=false

spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.bmt=INFO
